;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="CharacterStatus",DevComment="")
GameplayTagList=(Tag="CharacterStatus.IgnoreHitReact",DevComment="")
GameplayTagList=(Tag="CharacterStatus.PoiseBroken",DevComment="")
GameplayTagList=(Tag="CharacterStatus.SpecialAttackUnderway",DevComment="")
GameplayTagList=(Tag="CharacterStatus.Stunned",DevComment="")

